// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoueeoFWyiXqiLewZLpyjRm9rteKsh7M4',
    appId: '1:746602448270:web:f9ac487305400e90d550df',
    messagingSenderId: '746602448270',
    projectId: 'project-nuri-eojin',
    authDomain: 'project-nuri-eojin.firebaseapp.com',
    storageBucket: 'project-nuri-eojin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyOpXR6U8h39Gjxn2J8TzUchbf8pWYJNA',
    appId: '1:746602448270:android:d12bd2143c824341d550df',
    messagingSenderId: '746602448270',
    projectId: 'project-nuri-eojin',
    storageBucket: 'project-nuri-eojin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqAs8qyu7XgMlNt-bMPwMrnaEN4SXSR1I',
    appId: '1:746602448270:ios:c11791e729666bb1d550df',
    messagingSenderId: '746602448270',
    projectId: 'project-nuri-eojin',
    storageBucket: 'project-nuri-eojin.appspot.com',
    iosClientId: '746602448270-9ug0i7er2fm5eo7d5sjegrsopk9uo2rm.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqAs8qyu7XgMlNt-bMPwMrnaEN4SXSR1I',
    appId: '1:746602448270:ios:845c42d487eaf33ad550df',
    messagingSenderId: '746602448270',
    projectId: 'project-nuri-eojin',
    storageBucket: 'project-nuri-eojin.appspot.com',
    iosClientId: '746602448270-pp8tsin5qm16akovkkoge5qf72llm2ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamProject.RunnerTests',
  );
}
